# Generated by Django 6.0.2 on 2026-04-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_grandfather_existing_phone_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='license_number',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='user',
            name='license_photo',
            field=models.ImageField(blank=True, null=True, upload_to='users/license_photos/'),
        ),
        migrations.AddField(
            model_name='user',
            name='license_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='official_photo',
            field=models.ImageField(blank=True, null=True, upload_to='users/official_photos/'),
        ),
        migrations.AddField(
            model_name='user',
            name='official_photo_verified',
            field=models.BooleanField(default=False),
        ),
    ]
