# Generated by Django 6.0.2 on 2026-04-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_address_user_license_number_user_license_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='school_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='school_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='school_location_label',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
