# Generated by Django 6.0.2 on 2026-04-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_school_lat_user_school_lng_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneotp',
            name='purpose',
            field=models.CharField(choices=[('REGISTER', 'Passenger registration'), ('PASSWORD_RESET', 'Passenger password reset')], default='REGISTER', max_length=20),
        ),
    ]
