# Generated by Django 6.0.2 on 2026-04-19 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_authotp_delete_phoneotp_user_email_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('TRIP_STARTED', 'Trip Started'), ('TRIP_ENDED', 'Trip Ended'), ('PAYMENT_REQUESTED', 'Payment Requested'), ('ASSIGNMENT_UPDATED', 'Assignment Updated'), ('REVIEW_PROMPT', 'Review Prompt'), ('GENERAL', 'General')], default='GENERAL', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True, default='')),
                ('related_booking_id', models.IntegerField(blank=True, null=True)),
                ('related_trip_id', models.IntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='accounts_no_user_id_b29cd4_idx')],
            },
        ),
    ]
