# Generated by Django 5.2.3 on 2026-02-11 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transport', '0001_initial'),
        ('trips', '0002_triplocation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_stop_order', models.PositiveIntegerField()),
                ('to_stop_order', models.PositiveIntegerField()),
                ('seats_count', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('NO_SHOW', 'No show')], default='CONFIRMED', max_length=20)),
                ('fare_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_applied_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='trips.trip')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_seats', to='bookings.booking')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transport.seat')),
            ],
        ),
        migrations.CreateModel(
            name='OfflineBoarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_stop_order', models.PositiveIntegerField()),
                ('to_stop_order', models.PositiveIntegerField()),
                ('seats_count', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('helper', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offline_boardings', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_boardings', to='trips.trip')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfflineSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offline_boarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_seats', to='bookings.offlineboarding')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transport.seat')),
            ],
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('to_stop_order__gt', models.F('from_stop_order'))), name='chk_booking_to_gt_from'),
        ),
        migrations.AddConstraint(
            model_name='bookingseat',
            constraint=models.UniqueConstraint(fields=('booking', 'seat'), name='uniq_booking_seat'),
        ),
        migrations.AddConstraint(
            model_name='offlineboarding',
            constraint=models.CheckConstraint(condition=models.Q(('to_stop_order__gt', models.F('from_stop_order'))), name='chk_offline_to_gt_from'),
        ),
        migrations.AddConstraint(
            model_name='offlineseat',
            constraint=models.UniqueConstraint(fields=('offline_boarding', 'seat'), name='uniq_offline_boarding_seat'),
        ),
    ]
