# Generated by Django 6.0.2 on 2026-04-08 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_accepted_by_helper_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancellation_note',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancellation_reason',
            field=models.CharField(blank=True, choices=[('CHANGE_OF_PLANS', 'Change of plans'), ('WRONG_ROUTE', 'Booked the wrong route'), ('DELAY', 'Bus arrival delay'), ('PAYMENT_ISSUE', 'Payment issue'), ('EMERGENCY', 'Emergency or urgent issue'), ('LOGOUT', 'Passenger logged out mid-ride'), ('OTHER', 'Other')], default='', max_length=32),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
