# Generated by Django 6.0.2 on 2026-04-17 02:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_offlineboarding_payment_fields'),
        ('transport', '0003_bus_condition_bus_display_name_bus_exterior_photo_and_more'),
        ('trips', '0005_tripschedule_driver_assignment_accepted_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_stop_order', models.PositiveIntegerField()),
                ('to_stop_order', models.PositiveIntegerField()),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_holds', to=settings.AUTH_USER_MODEL)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seat_holds', to='transport.seat')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_holds', to='trips.trip')),
            ],
            options={
                'ordering': ['expires_at', 'created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('to_stop_order__gt', models.F('from_stop_order'))), name='chk_seat_hold_to_gt_from'), models.UniqueConstraint(fields=('trip', 'passenger', 'seat', 'from_stop_order', 'to_stop_order'), name='uniq_passenger_trip_seat_hold_scope')],
            },
        ),
    ]
