# Generated by Django 6.0.2 on 2026-04-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_bus_driver_bus_helper'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='condition',
            field=models.CharField(choices=[('NEW', 'New'), ('NORMAL', 'Normal'), ('OLD', 'Old')], default='NORMAL', max_length=20),
        ),
        migrations.AddField(
            model_name='bus',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='bus',
            name='exterior_photo',
            field=models.ImageField(blank=True, null=True, upload_to='buses/exterior/'),
        ),
        migrations.AddField(
            model_name='bus',
            name='interior_photo',
            field=models.ImageField(blank=True, null=True, upload_to='buses/interior/'),
        ),
        migrations.AddField(
            model_name='bus',
            name='layout_columns',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='bus',
            name='layout_rows',
            field=models.PositiveIntegerField(default=9),
        ),
        migrations.AddField(
            model_name='bus',
            name='model_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='seat_photo',
            field=models.ImageField(blank=True, null=True, upload_to='buses/seats/'),
        ),
    ]
