# Generated by Django 6.0.2 on 2026-04-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_tripsimulation'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='driver_end_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='driver_start_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='helper_end_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='helper_start_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
