# Generated by Django 6.0.2 on 2026-04-19 18:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0006_bus_route'),
        ('trips', '0005_tripschedule_driver_assignment_accepted_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TripExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('FUEL', 'Fuel'), ('REPAIR', 'Repair'), ('MAINTENANCE', 'Maintenance'), ('TOLL', 'Toll'), ('PARKING', 'Parking'), ('CLEANING', 'Cleaning'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('incurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='transport.bus')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trip_expenses', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='trips.trip')),
            ],
            options={
                'ordering': ['-incurred_at', '-created_at'],
            },
        ),
    ]
