# Generated by Django 6.0.2 on 2026-04-19 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_tripexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripschedule',
            name='helper_assignment_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
