# Generated by Django 6.0.2 on 2026-04-02 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('MOCK_ONLINE', 'Mock Online'), ('ESEWA', 'eSewa'), ('KHALTI', 'Khalti'), ('WALLET', 'Metro Wallet'), ('PASS', 'Ride Pass'), ('REWARD', 'Reward Ride')], max_length=20),
        ),
        migrations.CreateModel(
            name='PassengerWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reward_points', models.PositiveIntegerField(default=0)),
                ('lifetime_reward_points', models.PositiveIntegerField(default=0)),
                ('pass_rides_remaining', models.PositiveIntegerField(default=0)),
                ('pass_valid_until', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('passenger', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
