# Generated by Django 6.0.2 on 2026-04-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_method_passengerwallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengerwallet',
            name='pass_plan',
            field=models.CharField(blank=True, default='', max_length=24),
        ),
        migrations.AddField(
            model_name='passengerwallet',
            name='pass_total_rides',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
