from django.urls import path
from .views import (
    PassengerBookingsView,
    PassengerCancelBookingView,
    PassengerSeatHoldView,
    PassengerBookingReviewView,
    TripSeatAvailabilityView,
    CreateBookingView,
    CreateOfflineBoardingView,
    BookingDetailView,
    HelperBookingLookupView,
    HelperVerifyBookingOtpView,
    HelperAcceptBookingView,
    HelperBoardBookingView,
    HelperRequestBookingPaymentView,
    HelperCompleteBookingView,
    OfflineCollectCashView,
    OfflineCompleteView,
)

urlpatterns = [
    path("my/", PassengerBookingsView.as_view(), name="passenger-bookings"),
    path("<int:booking_id>/", BookingDetailView.as_view(), name="booking-detail"),
    path("<int:booking_id>/cancel/", PassengerCancelBookingView.as_view(), name="booking-cancel"),
    path("<int:booking_id>/review/", PassengerBookingReviewView.as_view(), name="booking-review"),
    path("lookup/", HelperBookingLookupView.as_view(), name="booking-lookup"),
    path("otp/verify/", HelperVerifyBookingOtpView.as_view(), name="booking-otp-verify"),
    path("trips/<int:trip_id>/availability/", TripSeatAvailabilityView.as_view(), name="trip-seat-availability"),
    path("trips/<int:trip_id>/holds/", PassengerSeatHoldView.as_view(), name="trip-seat-holds"),
    path("trips/<int:trip_id>/book/", CreateBookingView.as_view(), name="trip-book"),
    path("trips/<int:trip_id>/offline/", CreateOfflineBoardingView.as_view(), name="trip-offline"),
    path("<int:booking_id>/accept/", HelperAcceptBookingView.as_view(), name="booking-accept"),
    path("<int:booking_id>/request-payment/", HelperRequestBookingPaymentView.as_view(), name="booking-request-payment"),
    path("<int:booking_id>/board/", HelperBoardBookingView.as_view(), name="booking-board"),
    path("<int:booking_id>/complete/", HelperCompleteBookingView.as_view(), name="booking-complete"),
    path("offline/<int:offline_boarding_id>/collect-cash/", OfflineCollectCashView.as_view(), name="offline-collect-cash"),
    path("offline/<int:offline_boarding_id>/complete/", OfflineCompleteView.as_view(), name="offline-complete"),
]
